export enum UssdState {
  INITIAL = 'INITIAL',
  SIGNUP_FIRST_NAME = 'SIGNUP_FIRST_NAME',
  SIGNUP_LAST_NAME = 'SIGNUP_LAST_NAME',
  SIGNUP_ID_NUMBER = 'SIGNUP_ID_NUMBER',
  SIGNUP_PIN = 'SIGNUP_PIN',
  SIGNUP_CONFIRM_PIN = 'SIGNUP_CONFIRM_PIN',
  LOGIN_PIN = 'LOGIN_PIN',
}
