export enum Permission {
  CREATE_USER = 'create_user',
  READ_USER = 'read_user',
  UPDATE_USER = 'update_user',
  DELETE_USER = 'delete_user',
  CREATE_QUOTATION = 'create_quotation',
  APPROVE_QUOTATION = 'approve_quotation',
  READ_QUOTATION = 'read_quotation',
  UPDATE_QUOTATION = 'update_quotation',
  MANAGE_INSURANCE_SERVICES = 'manage_insurance_services',
  MANAGE_PREMIUM_RATES = 'manage_premium_rates',
  MANAGE_VEHICLES = 'manage_vehicles',
  PROCESS_PAYMENTS = 'process_payments',
  MANAGE_REFUNDS = 'manage_refunds',
  MANAGE_SYSTEM_SETTINGS = 'manage_system_settings',
  VIEW_REPORTS = 'view_reports',
  MANAGE_NOTIFICATIONS = 'manage_notifications',
}
